### ISSUE TITLE
gw2 launch buddy without administrative privileges crashes

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#137]
After issue #122 which caused launch buddy to require opening in administrative privilege mode, I modified the program to remove the UAC file, and updated my windows settings to allow access to symlinks on my user account.

I recently updated to a newer version of the code, and I now get the following exception when trying to run:

Unhandled Exception: System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessTimes()
   at System.Diagnostics.Process.get_StartTime()
   at Gw2_Launchbuddy.ObjectManagers.ClientManager.ImportActiveClients() in C:\Users\Jake\Documents\git\Gw2_Launchbuddy\Gw2 Launchbuddy\ObjectManagers\ClientManager.cs:line 112
   at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.Init() in C:\Users\Jake\Documents\git\Gw2_Launchbuddy\Gw2 Launchbuddy\ObjectManagers\EnviromentManager.cs:line 70
   at Gw2_Launchbuddy.EntryPoint.RunParsed(LaunchOptions options) in C:\Users\Jake\Documents\git\Gw2_Launchbuddy\Gw2 Launchbuddy\App.xaml.cs:line 30
   at Gw2_Launchbuddy.EntryPoint.<>c.<Main>b__1_0(LaunchOptions options) in C:\Users\Jake\Documents\git\Gw2_Launchbuddy\Gw2 Launchbuddy\App.xaml.cs:line 25
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Gw2_Launchbuddy.EntryPoint.Main(String[] args) in C:\Users\Jake\Documents\git\Gw2_Launchbuddy\Gw2 Launchbuddy\App.xaml.cs:line 25
The program '[13380] Gw2 Launchbuddy.exe' has exited with code 0 (0x0).

**Comment by jacob-keller** [comment]
I'm not sure if it was a recent change or not, but it's very annoying to require opening launch buddy in administrator mode because it then launches the actual gw2 accounts in admin mode as well.

Any idea why this is access denied?

**Comment by jacob-keller** [comment]
I'm not sure what happened, but I re-built and things seem to be working again...
