### ISSUE TITLE
LB open crash

### ISSUE THREAD

**Issue by fashionkid** [TheCheatsrichter/Gw2_Launchbuddy#176]
LB just crashes when I try to open it. I tied to open with admin or use developer mod. I treid different versions but nothing works. Here is the report. I do not know how to solve it.
Exception Type:
System.Windows.Markup.XamlParseException

Message: 
The invocation of the constructor on type 'Gw2_Launchbuddy.MainWindow' that matches the specified binding constraints threw an exception.

Source:
PresentationFramework

Stack Trace:
System.Exception: Could not create Symbolic Local dat link.
Provided Local.dat file does not exist or Linkfile is already created. ---> System.Exception: Provided Local.dat file does not exist or Linkfile is already created.
   at Gw2_Launchbuddy.Modifiers.LocalDatManager.CreateSymbolLink(String sourcefile)
   --- End of inner exception stack trace ---
   at Gw2_Launchbuddy.Modifiers.LocalDatManager.CreateSymbolLink(String sourcefile)
   at Gw2_Launchbuddy.Modifiers.LocalDatManager.Apply(LocalDatFile file)
   at Gw2_Launchbuddy.Modifiers.LocalDatManager.UpdateLocalDat(LocalDatFile file, Boolean forced)
   at Gw2_Launchbuddy.ObjectManagers.AccountManager.UpdateAccountFiles()
   at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.AfterUI_Inits()
   at Gw2_Launchbuddy.MainWindow.Init()\n   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Gw2_Launchbuddy.EntryPoint.RunParsed()
   at Gw2_Launchbuddy.EntryPoint.Main(String[] args)
Please help, Thanks!

**Comment by TheCheatsrichter** [comment]
Try to delete the following file:

%appdata%/Gw2 Launchbuddy/Accs.xml
and
%appdata%/Gw2 Launchbuddy/Addons.xml

this will delete your all your settings and should give you a clean start

**Comment by fashionkid** [comment]
nice, Problem solved! Thank u!
