### ISSUE TITLE
just keeps crashing.... 

### ISSUE THREAD

**Issue by Master-Liu-TBF** [TheCheatsrichter/Gw2_Launchbuddy#332]
so a while back i was using 2.4.2 and was having an issue that somehow couldn't be resolved so i started using another launcher to do what i needed... and thought to myself maybe LB is updated and i can go back to using that one:

Gw2 Launchbuddy 3.0.4.0 Crash Report

Windows Version
Microsoft Windows 10 Pro 64-bit (OS Build 19043)

CLR Version
4.0.30319.42000

Exception

Exception Type
System.Windows.Markup.XamlParseException

Error Message
The invocation of the constructor on type 'Gw2_Launchbuddy.MainWindow' that matches the specified binding constraints threw an exception.

Source
PresentationFramework

Stack Trace
at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
at System.Windows.Application.DoStartup()
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperation.Invoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at Gw2_Launchbuddy.EntryPoint.RunParsed()
at Gw2_Launchbuddy.EntryPoint.Main(String[] args)

Inner Exception

Exception Type
System.ComponentModel.Win32Exception

Error Message
The system cannot find the file specified

Source
System

Stack Trace
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.UpdateGwClient(Boolean isforced)
at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.CheckGwClientVersion()
at Gw2_Launchbuddy.ObjectManagers.EnviromentManager.AfterUI_Inits()
at Gw2_Launchbuddy.MainWindow.Init()

so long story is that even if i try to use a previous version, i get the same crash.... the reports have been sent to the developer. but i figured that maybe this would help too. ive deleted, redownloaded, unblocked it, allowed it, restarted my system.... and it just wont work. any suggestions, tips, tricks? or is it just plain ol' user error?

i also tried looking at the processes to see if there's anything i missed and i dont want to start messing with things and have things get even worse.

**Comment by TheCheatsrichter** [comment]
Seems to be a configfile that got corrupted.

Delete "C:\Users\YOURNAME\AppData\Roaming\Gw2 Launchbuddy\LBConfig.xml" and try again

**Comment by Fribb** [comment]
I had the same issue even across versions and while resetting the whole config worked (including accounts) I think it wasn't because of LB. When LB crashed I tried launching the GW2 client normally but windows told me that it couldn't execute this without any reason.

After trying it again, the GW2 client started and LB could start again even with the existing configuration.

Maybe since LB start the client on startup which would crash without reason also makes LB crash.
